###############################################################
#  Generated by:      Cadence Innovus 17.12-s095_1
#  OS:                Linux x86_64(Host ID eecad33)
#  Generated on:      Thu Apr 11 18:56:38 2019
#  Design:            conv_pool
#  Command:           create_ccopt_clock_tree_spec -filename ./ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# Clocks present at pin clk
#   clk (period 1200.0ps) in timing_config common([/afs/asu.edu/users/n/b/e/nbeste/asap7_rundir/1/top.1200.syn.v])
create_ccopt_clock_tree -name clk -source clk -no_skew_group

# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk 1200

# Skew group to balance non generated clock:clk in timing_config:common (sdc /afs/asu.edu/users/n/b/e/nbeste/asap7_rundir/1/conv_pool.1200.syn.v)
create_ccopt_skew_group -name clk/common -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/common true
set_ccopt_property extracted_from_clock_name -skew_group clk/common clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk/common common
set_ccopt_property extracted_from_delay_corners -skew_group clk/common {delayCorner_slow delayCorner_fast}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

